# fly.toml app configuration file generated for wellness-platform-api on 2025-07-15T10:12:18+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wellness-platform-api'
primary_region = 'sin'

[build]

[env]
  NODE_ENV = 'production'
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[checks]
  [checks.health]
    port = 3000
    type = 'http'
    interval = '15s'
    timeout = '10s'
    grace_period = '30s'
    method = 'GET'
    path = '/api/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
